/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/login/form.vue')['default']
    FormLogin: typeof import('./src/components/login/formLogin.vue')['default']
    HomeFooter: typeof import('./src/components/HomePage/home-footer.vue')['default']
    HomeHeader: typeof import('./src/components/HomePage/home-header.vue')['default']
    HomeSidebar: typeof import('./src/components/HomePage/home-sidebar.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    LoginQr: typeof import('./src/components/Login/login-qr.vue')['default']
    QrCodeLogin: typeof import('./src/components/Login/components/qrCodeLogin/index.vue')['default']
    Qrform: typeof import('./src/components/login/Qrform.vue')['default']
    Qrimg: typeof import('./src/components/login/Qrimg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanSearch: typeof import('vant/es')['Search']
    VerifyCodeLogin: typeof import('./src/components/Login/components/verifyCodeLogin/index.vue')['default']
  }
}
